# Generated by Django 6.0.1 on 2026-05-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
        ('core', '0005_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_shop', to='core.shop'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_shop', to='core.shop'),
        ),
    ]
