# Generated by Django 6.0.1 on 2026-02-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialkey',
            name='allow_inventory',
            field=models.BooleanField(default=False, help_text='Toggle this to allow access to the Inventory App'),
        ),
    ]
