# Generated by Django 6.0.1 on 2026-03-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serialkey_allow_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialkey',
            name='allow_hr',
            field=models.BooleanField(default=False, help_text='Toggle this to allow access to the HR & Payroll App'),
        ),
    ]
