# Generated by Django 6.0.1 on 2026-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_serialkey_allow_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialkey',
            name='allow_finance',
            field=models.BooleanField(default=False, help_text='Toggle this to allow access to the Finance & Expense App'),
        ),
    ]
