# Generated by Django 6.0.1 on 2026-05-11 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employer_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_employees', to='core.shop'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Shop Admin'), ('MANAGER', 'Manager'), ('CLERK', 'Inventory Clerk'), ('CASHIER', 'Cashier')], default='ADMIN', max_length=20),
        ),
    ]
